name: Build Cloud Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run weekly on Monday at 00:00 UTC
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  build-images:
    strategy:
      matrix:
        system: [x86_64-linux]
        image: [aws, gcp, azure]
        include:
          - system: x86_64-linux
            runner: ubuntu-latest
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-25.05
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Build ${{ matrix.image }} image for ${{ matrix.system }}
        run: |
          nix build .#packages.${{ matrix.system }}.${{ matrix.image }} --print-build-logs

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.image }}-${{ matrix.system }}-image
          path: result/*
          retention-days: 7
